### ISSUE TITLE
How to shorten the training time?

### ISSUE THREAD

**Issue by Affan-Hillergrand** [ChanganVR/RelationalGraphLearning#6]
Hello!  Your excellent work is very helpful to me. However, I had some questions when using your code training strategy.
Now I am using an NVIDIA gtx1080 graphics card, which takes about 20 hours for 10000 episodes. And the utilization rate of graphics card computing power in training is very low. 
May I ask you about the equipment you used when you were training and how long did it take you to train each time? And are there any techniques that can be used to improve training efficiency?
Thank you!

**Comment by ChanganVR** [comment]
Hi, thank you for your interest. I trained the policy on CPU and the training time was roughly the same as yours or even less. I experimented with GPU training and found it did not speed up the trainig. I think the reason is that the crowd simulation is done on CPU and the bottleneck is on the crowd simulation. Some optimization should definitely help speed up the simulation & training, however, I don't have time  to investigate this. But I encourage you to explore that as it would help you gain a deeper understanding of the code.

**Comment by Affan-Hillergrand** [comment]
Thank you for your helpful reply. I will continue to explore this code and try to speed up the training process.

**Comment by ainoxus** [comment]
@Affan-Hillergrand 

Hi! I am commenting here because I cannot find an "Issues" tab in the latest - just a few months old - [`ComplexityNav`](https://github.com/fluentrobotics/ComplexityNav) repository. Obviously, it has been a while, and GPU hardware is now much more advanced than it was when this repository was first released.

**I was wondering whether you were able to improve the training time by using a GPU?**

I tried using an `Nvidia GeForce RTX 3050 Ti Laptop` GPU with the newest code from the [`ComplexityNav`](https://github.com/fluentrobotics/ComplexityNav) repository and it was taking more than 17 hours.

**If you were able to shift the load to the GPU and speed up the training, could you please share which parts of the code (from this repository or the newer one) did you change?**

It would really help a lot. Thanks!
